server:
  grpcPort: 9092
  environment: "development"
  logLevel: "debug"

nats:
  url: "http://nats:4222"
  maxReconnect: 10
  reconnectWaitSeconds: 2
  timeoutSeconds: 5

redis:
  address: "redis:6379"
  password: ""