aws:
  region: "us-east-1"
  endpoint: "http://localhost:8000"

dynamodb:
  tableName: "GoodSwipe"
  maxRetries: 3
  useLocalEndpoint: true

server:
  grpcPort: 9091
  environment: "development"
  logLevel: "debug"

scheduler:
  tournamentDurationInHour: 24