aws:
  region: "us-east-1"
  endpoint: "http://dynamodb:8000"

dynamodb:
  tableName: "GoodSwipe"
  maxRetries: 3
  useLocalEndpoint: true

server:
  grpcPort: 9091
  environment: "development"
  logLevel: "debug"

nats:
  url: "http://nats:4222"
  maxReconnect: 10
  reconnectWaitSeconds: 2
  timeoutSeconds: 5