aws:
  region: "us-east-1"
  endpoint: "http://dynamodb:8000"

dynamodb:
  tableName: "GoodSwipe"
  maxRetries: 3
  useLocalEndpoint: true

server:
  grpcPort: 9090
  environment: "development"
  logLevel: "debug"